data:
  title_size: 30
  his_size: 50
  data_format: news
  npratio: 4
  
info:
  metrics:
  - group_auc
  - mean_mrr
  - ndcg@5;10
  show_step: 100000
  
model:
  attention_hidden_dim: 200
  word_emb_dim: 300
  dropout: 0.25
  head_num: 20
  head_dim: 20
  model_type: nrms

train:
  batch_size: 32
  epochs: 10
  learning_rate: 0.0002
  loss: categorical_crossentropy
  support_quick_scoring: true
  show_step: 10
